spring:
  application:
    name : kkinikong
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect

  jwt:
    secret: ${JWT_SECRET}
    access:
      token:
        expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    stack:
      auto: false

openai:
    api:
        key: ${OPEN_API_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: desc
    tags_sorter: alpha
    operations_sorter: method # delete - get - patch - post - put 정렬
  use-fqn: true