spring:
  application:
    name : kkinikong
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: never # 기본값은 never 최초, 한 번만 always 로 바꾸어서 실행 후 다시 never 로 돌리기
      schema-locations: classpath:/org/springframework/batch/core/schema-mysql.sql

  batch:
    job:
      enabled: false
