spring:
  application:
    name : kkinikong
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: ${JWT_SECRET}
    access:
      token:
        expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}

  sql:
    init:
      mode: never
      schema-locations: classpath:/org/springframework/batch/core/schema-mysql.sql

  batch:
    job:
      enabled: false

csv:
  upload-dir: ${CSV_UPLOAD_DIR}
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
        bucket: ${AWS_S3_BUCKET_NAME}
    stack:
      auto: false