spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      port: ${REDIS_PORT}

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    url: http://localhost:8080/v3/api-docs
  api-docs:
    path: /v3/api-docs