#!/bin/sh

MSG_FILE=$1
BRANCH_NAME=$(git symbolic-ref --short HEAD)
ISSUE_KEY=$(echo "$BRANCH_NAME" | grep -oE '[A-Z]+-[0-9]+')

if [ -n "$ISSUE_KEY" ] && ! grep -q "$ISSUE_KEY" "$MSG_FILE"; then
  sed -i.bak -e "1s/^/[$ISSUE_KEY] /" "$MSG_FILE"
fi
