name: CD - Blue-Green Deploy to EC2

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Deploy to EC2 (Blue-Green)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "🔎 현재 실행 중인 컨테이너 확인"
            RUNNING=$(docker ps --format '{{.Names}}' | grep spring-blue || true)

            if [ "$RUNNING" = "spring-blue" ]; then
              echo "✅ 현재 blue가 운영 중 -> green 배포 시작"
              docker rm -f spring-green || true
              docker pull chaeeunkim/kkini-kong-be:develop
              docker run -d --name spring-green -p 8081:8080 chaeeunkim/kkini-kong-be:develop

              echo "🔧 nginx 설정을 green으로 변경"
              sudo sed -i 's/8080/8081/g' /etc/nginx/conf.d/default.conf
              sudo nginx -s reload

              echo "🧹 기존 blue 컨테이너 종료"
              docker rm -f spring-blue || true

            else
              echo "✅ 현재 green이 운영 중 -> blue 배포 시작"
              docker rm -f spring-blue || true
              docker pull chaeeunkim/kkini-kong-be:develop
              docker run -d --name spring-blue -p 8080:8080 chaeeunkim/kkini-kong-be:develop

              echo "🔧 nginx 설정을 blue으로 변경"
              sudo sed -i 's/8081/8080/g' /etc/nginx/conf.d/default.conf
              sudo nginx -s reload

              echo "🧹 기존 green 컨테이너 종료"
              docker rm -f spring-green || true
            fi

            echo "✅ 배포 완료!"